dev updated, and we are going to new server

diff --git a/bin/nginxmgr b/bin/nginxmgr
--- a/bin/nginxmgr
+++ b/bin/nginxmgr
@@ -1,5 +1,15 @@
 #!/bin/sh
 
+# check
+function Check() {
+	local current=`ps aux | egrep "nginx: [a-z]{6} process" | grep -v 'grep' | wc -l`
+	if [[ $current -gt 0 ]]; then
+		return 1
+	else
+		return 0
+	fi
+}
+
 # kill nginx
 function Stop() {
 	local current=`ps aux | egrep "nginx: [a-z]{6} process" | grep -v 'grep' | awk '{ print $2 }'`
@@ -7,16 +17,40 @@ function Stop() {
 		echo "Killing Process ID: ${id}";
 		sudo kill -9 ${id};
 	done
+	Check
+	if [[ $? -eq 0 ]]; then
+		echo -e "[\e[32m OK \e[0m] stop nginx success"
+	else
+		echo -e "[\e[31m FAILED \e[0m] stop nginx fail"
+	fi
 }
 
 # restart
 function Start() {
 	sudo nginx -c /home/ubuntu/web/nginx/conf/nginx.conf
+	Check
+	if [[ $? -eq 1 ]]; then
+		echo -e "[\e[32m OK \e[0m] start nginx success"
+	else
+		echo -e "[\e[31m FAILED \e[0m] start nginx fail"
+	fi
 }
 
-function Helper() {
-	echo "Usage: $1 <start | stop | restart>"
+# status
+function Status() {
+	Check
+	if [[ $? -eq 1 ]]; then
+		echo -e "[\e[32m Running \e[0m] nginx is running"
+	else
+		echo -e "[\e[31m Stopped \e[0m] nginx is stopped"
+	fi
 }
+
+# print helper
+function Helper() {
+	echo "Usage: $1 <start | stop | restart | status>"
+}
+
 
 if [[ $# != 1 ]]; then
 	Helper $0
@@ -32,6 +66,9 @@ else
 		"restart")
 			Stop
 			Start
+			;;
+		"status")
+			Status
 			;;
 		*)
 			Helper $0
